language: node_js
node_js:
- '6.2'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
before_deploy:
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: kPACncSHCmyrZj6VcvmdvZ2abtvgHVaKl4D64pnEqxigH5J9LLgORNV+AFM1DjO4d6uHVQrLszl2j/8voWdZT0ECdpznd4pmKqVSWdfLMmh0DgqnFCG3Q7B/n7ym0/2LFIqM7UYxknVtr9FJzT3arORuqEt1paqqqrrBrpBWi4nfoMRUQvTLtPStbCjFErLb/MJVbF0lZVky3YUj/47TKn9tEbcuZdaxDD1bsiaE67JfXYdC1N3bdQYSG2j40u4qs2p6SzLctA09GHkZyuQyFH2vLeehkalgIFVDBvyV9oe+0ogbykgzqlPwZCWt/djMC7MP3weHcw0wSJgJEQ8l/xsglNJY3ME7FZ/gTjulCM6Yir8YkrqWFW7Wlvi/bUE6eRZpW9QNEr65oQWVKUHLbdO+06JIkkfzhLyrdroQJQSUqcioRLQ0GQRWBW+oStzGqq3NIFUROfDIloNRRUvS/laXiBCTMq2nPe05fn8ZeHIgSrpNt6ONTl6XI6ERXiLiD76KHHSfgBuhzHZ26TpllIPvnzyxTtzMVjgCRXmfF6L0FQriSWcI1HR6S9heqfDYFXttmnZyagQHu7aAcuBPikjXC2lLUJEVaROhaaqT0C2ddPUiOcXY9ER/mdpxJbd8PlRzR/ZOK1G9spQ7GnGKT4S/RQoyE7GaoiPLUAerbII=
